#! /bin/sh

# mouse pointer
xsetroot -cursor_name left_ptr &

# keylock - uncomment the below line if you need indicator
indicator-keylock &

# first kill the background-changer that could possibly respawn
# and start it immediately from within the same script - 
bash ~/.config/system_scripts/pkill_bc

# initiate sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

## loading workspaces first
bspc monitor -d I II III IV V VI VII VIII

## bar 
killall tint2
tint2 -c ~/.config/tint2/bspwm/bspwm.tint2rc &

## compositor
picom -b --config ~/.config/picom/picom.conf --experimental-backends
 
## lock settings
xautolock -time 5 -locker ~/.config/system_scripts/session_lock &

# battery [if on AC permanently, then comment out 
# the below line ]
lxqt-powermanagement &

# network
killall cmst
cmst -m &

## attachment alert
udiskie -A &

## info-center [remove the line below to remove it from autostart]
welcomeapp 

## bspc config and rule settings

bspc config border_width         1
bspc config window_gap          5

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# specify your custom rules here.
# I have kept one as an example.
bspc rule -a welcomeapp state=tiled
